language: generic

services:
  - docker

before_install:
  - docker pull matz0xe/spack
  - docker run -v $PWD:/source -w /source bluebrain/spack spack diy --run-tests mvdtool@develop

script: "ruby -ne 'puts $_ if /^==>.*make.*test/../.*phase.*install/ and not /^==>|make: \\*\\*\\*/' spack-build.out"
